### ISSUE TITLE
v2/client: move to async reqwest

### ISSUE THREAD

**Issue by lucab** [camallo/dkregistry-rs#44]
Now that reqwest has an [async](https://docs.rs/reqwest/0.9.2/reqwest/async/index.html) module, we should use that instead of plain hyper. Unfortunately, this means switching from rustls to native-tls, thus getting a FFI dependency to openssl (or similar).

---
Progress
- [x] src/v2/blobs.rs
- [x] src/v2/tags.rs
- [x] src/v2/manifest/mod.rs
- [ ] src/v2/auth.rs #95 
- [ ] src/v2/catalog.rs #95
- [ ] src/v2/mod.rs #95
- [ ] src/v2/config.rs #95 
- [ ] src/lib.rs #95
- [ ] src/errors.rs #95

**Comment by lucab** [comment]
@steveeJ both are still in development and will likely see a major rework once [futures land in stdlib](https://doc.rust-lang.org/nightly/std/future/index.html). However hyper is the wrong layer to use when implementing an HTTP client, which means that we poorly re-implement here some middleware logic (e.g. [following redirections](https://github.com/camallo/dkregistry-rs/blob/bacca3b7fb80edf7c38035d6f355672aa2536dd4/src/v2/blobs.rs#L48-L83)).

This crate status quo is is purely a result of historical timing, as at that point there was no higher-level async HTTP client.

**Comment by steveeJ** [comment]
> However hyper is the wrong layer to use when implementing an HTTP client, which means that we poorly re-implement here some middleware logic (e.g. [following redirections](https://github.com/camallo/dkregistry-rs/blob/bacca3b7fb80edf7c38035d6f355672aa2536dd4/src/v2/blobs.rs#L48-L83)).
> 
> This crate status quo is is purely a result of historical timing, as at that point there was no higher-level async HTTP client.

I understand your concern. If we need to extend the functionality of dkregistry we can refactor the code to use *reqwest* along that. Personally I don't have the urge to do it earlier, but of course I'm not stopping you from doing it ;-)

**Comment by steveeJ** [comment]
The close was unintentional via a stale `Fixes ..` in a PR.
Marking this as a bug because it causes the system certificate store to be ignored, which is the default behavior of `hyper-rustls`.
